# Generated by Django 3.0.2 on 2020-02-21 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('sifra_predmeta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('naziv_predmeta', models.CharField(max_length=200)),
                ('datum_ispita', models.DateTimeField(blank=True, null=True)),
                ('semestar', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=200)),
                ('espb_bodova', models.IntegerField(null=True)),
                ('vrsta_predmeta', models.CharField(blank=True, choices=[('Obavezni', 'Obavezni'), ('Izborni', 'Izborni')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Predmeti',
                'ordering': ['semestar', 'smer'],
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezime_i_ime', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Profesori',
                'ordering': ['prezime_i_ime'],
            },
        ),
        migrations.CreateModel(
            name='Smer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_smera', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Smerovi',
                'ordering': ['naziv_smera'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ime_studenta', models.CharField(max_length=200)),
                ('prezime_studenta', models.CharField(max_length=200)),
                ('br_indexa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('jmbg', models.CharField(max_length=13)),
                ('god_studija', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=200)),
                ('predmeti', models.ManyToManyField(to='login.Predmet')),
                ('smer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Smer')),
            ],
            options={
                'verbose_name_plural': 'Studenti',
            },
        ),
        migrations.AddField(
            model_name='predmet',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Profesor'),
        ),
        migrations.AddField(
            model_name='predmet',
            name='smer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Smer'),
        ),
    ]
