# Generated by Django 3.0.2 on 2020-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predmet',
            options={'ordering': ['semestar', 'sifra_predmeta'], 'verbose_name_plural': 'Predmeti'},
        ),
        migrations.RemoveField(
            model_name='predmet',
            name='smer',
        ),
        migrations.AddField(
            model_name='predmet',
            name='smer',
            field=models.ManyToManyField(to='login.Smer'),
        ),
    ]
