# Generated by Django 3.0.2 on 2020-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='prijava',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
